import type { Lang } from './i18n/index.ts';

/** 转换器实现，对应 src/lib/converters/ 下的模块 */
export type ConverterId =
  // 第一批
  | 'html'
  | 'docx'
  | 'pdf'
  | 'text'
  | 'turndown'
  // A 档：纯文本映射，基于 ast.ts 的 token 树
  | 'latex'
  | 'rst'
  | 'confluence'
  | 'latexToMd'
  | 'csvToTable'
  | 'jsonToTable'
  | 'tableToCsv'
  // B 档：复用现有管线
  | 'tableToPdf'
  | 'tableToImage'
  | 'editor'
  // C 档：外部解析（docx / pdf 走二进制输入）
  | 'wordToMd'
  | 'pdfToMd'
  | 'mdToImage';

type I18nText = Partial<Record<Lang, string>> & { en: string };

export interface ToolDef {
  slug: string;
  converter: ConverterId;
  /** md-out：Markdown 是输入；md-in：Markdown 是输出 */
  direction: 'md-out' | 'md-in';
  /**
   * 输出面板用哪种控件：
   *   html -> 渲染成预览（word / pdf 这类看重最终样式的）
   *   text -> 只读文本框（纯文本 / 源码，必须能原样复制）
   * 注意它和 direction 是两件事：markdown-to-text 输入是 Markdown（md-out），
   * 但产物是纯文本，塞进预览 div 会被当 HTML 解析，所以必须是 text。
   */
  outputKind: 'html' | 'text';
  outputExt: string;
  /** 输入面板允许拖入的文件后缀 */
  accept: string;
  /** 决定输入面板的示例文档、占位符与面板标题 */
  inputKind: 'md' | 'html' | 'csv' | 'json' | 'latex' | 'file';
  /**
   * Word 与 PDF 是二进制格式，只能以文件形式给进来，
   * 粘贴文本没有意义，草稿也不该存进 localStorage。
   */
  binary?: boolean;
  name: I18nText;
  seoTitle: I18nText;
  seoDesc: I18nText;
  h1: I18nText;
  intro: I18nText;
}

/**
 * 工具注册表 —— 整个站点的单一数据源。
 * 加一个新工具 = 加一条配置 + 在 lib/converters 里加一个实现，
 * 7 种语言的页面会自动生成。
 *
 * 七种语言都要填齐，否则该语言页会回落到英文，
 * 出现「路由是本地语言、内容却是英文」的假本地化。
 */
export const TOOLS: ToolDef[] = [
  {
    slug: 'markdown-to-word',
    converter: 'docx',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'docx',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to Word',
      'zh-cn': 'Markdown 转 Word',
      'zh-tw': 'Markdown 轉 Word',
      ja: 'Markdown → Word',
      fr: 'Markdown vers Word',
      pt: 'Markdown para Word',
      de: 'Markdown zu Word',
    },
    seoTitle: {
      en: 'Convert MD to Word (Docx) Online - Free Markdown to Word',
      'zh-cn': 'Markdown 转 Word 在线工具 - 免费 Docx 导出',
      'zh-tw': 'Markdown 轉 Word 線上工具 - 免費 Docx 匯出',
      ja: 'Markdown を Word（Docx）に変換 - 無料オンラインツール',
      fr: 'Convertir Markdown en Word (Docx) en ligne - Gratuit',
      pt: 'Converter Markdown para Word (Docx) online - Grátis',
      de: 'Markdown in Word (Docx) online umwandeln - Kostenlos',
    },
    seoDesc: {
      en: 'Convert Markdown to Word (.docx) free in your browser. Code blocks, tables and images preserved. No signup, no upload.',
      'zh-cn': '免费在线将 Markdown 转为 Word 文档，保留代码块、表格与图片，无需注册，本地处理不上传。',
      'zh-tw': '免費線上將 Markdown 轉為 Word 文件，保留程式碼區塊、表格與圖片，無需註冊，本機處理不上傳。',
      ja: 'Markdown を無料で Word（.docx）に変換。コードブロック、表、画像も保持。登録不要、アップロード不要。',
      fr: 'Convertissez gratuitement Markdown en Word (.docx) dans votre navigateur. Blocs de code, tableaux et images conservés. Sans inscription, sans envoi.',
      pt: 'Converta Markdown para Word (.docx) grátis no navegador. Blocos de código, tabelas e imagens preservados. Sem cadastro, sem upload.',
      de: 'Wandeln Sie Markdown kostenlos im Browser in Word (.docx) um. Codeblöcke, Tabellen und Bilder bleiben erhalten. Keine Anmeldung, kein Upload.',
    },
    h1: {
      en: 'Free Markdown to Word Converter',
      'zh-cn': '免费 Markdown 转 Word 转换器',
      'zh-tw': '免費 Markdown 轉 Word 轉換器',
      ja: '無料の Markdown → Word 変換ツール',
      fr: 'Convertisseur Markdown vers Word gratuit',
      pt: 'Conversor gratuito de Markdown para Word',
      de: 'Kostenloser Markdown-zu-Word-Konverter',
    },
    intro: {
      en: 'Export clean .docx files with headings, code blocks, tables and images intact. Everything runs locally — your content never leaves the device.',
      'zh-cn': '导出干净的 .docx 文件，完整保留标题、代码块、表格与图片。全部在本地浏览器完成，内容不会离开你的设备。',
      'zh-tw': '匯出乾淨的 .docx 檔案，完整保留標題、程式碼區塊、表格與圖片。全部在本機瀏覽器完成，內容不會離開你的裝置。',
      ja: '見出し、コードブロック、表、画像を保ったまま .docx を書き出せます。すべてブラウザ内で完結し、内容が端末から外に出ることはありません。',
      fr: 'Exportez des fichiers .docx propres avec titres, blocs de code, tableaux et images intacts. Tout se fait localement — votre contenu ne quitte jamais l\'appareil.',
      pt: 'Exporte arquivos .docx limpos com títulos, blocos de código, tabelas e imagens intactos. Tudo roda localmente — seu conteúdo nunca sai do dispositivo.',
      de: 'Exportieren Sie saubere .docx-Dateien mit intakten Überschriften, Codeblöcken, Tabellen und Bildern. Alles läuft lokal — Ihre Inhalte verlassen das Gerät nicht.',
    },
  },
  {
    slug: 'markdown-to-pdf',
    converter: 'pdf',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'pdf',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to PDF',
      'zh-cn': 'Markdown 转 PDF',
      'zh-tw': 'Markdown 轉 PDF',
      ja: 'Markdown → PDF',
      fr: 'Markdown vers PDF',
      pt: 'Markdown para PDF',
      de: 'Markdown zu PDF',
    },
    seoTitle: {
      en: 'Convert Markdown to PDF Online - Free & Vector Output',
      'zh-cn': 'Markdown 转 PDF 在线工具 - 矢量输出、文字可选',
      'zh-tw': 'Markdown 轉 PDF 線上工具 - 向量輸出、文字可選',
      ja: 'Markdown を PDF に変換 - ベクター出力・テキスト選択可',
      fr: 'Convertir Markdown en PDF en ligne - Sortie vectorielle',
      pt: 'Converter Markdown para PDF online - Saída vetorial',
      de: 'Markdown in PDF online umwandeln - Vektorausgabe',
    },
    seoDesc: {
      en: 'Turn Markdown into a selectable, searchable vector PDF using your browser print engine. No bitmap, no upload, no signup.',
      'zh-cn': '用浏览器打印引擎把 Markdown 变成可选中、可搜索的矢量 PDF。非截图位图，无需上传与注册。',
      'zh-tw': '用瀏覽器列印引擎把 Markdown 變成可選取、可搜尋的向量 PDF。非截圖點陣圖，無需上傳與註冊。',
      ja: 'ブラウザの印刷エンジンで Markdown を選択・検索可能なベクター PDF に。画像のキャプチャではありません。アップロードも登録も不要。',
      fr: 'Transformez Markdown en PDF vectoriel sélectionnable et recherchable via le moteur d\'impression du navigateur. Pas de bitmap, pas d\'envoi, sans inscription.',
      pt: 'Transforme Markdown em PDF vetorial selecionável e pesquisável com o motor de impressão do navegador. Sem bitmap, sem upload, sem cadastro.',
      de: 'Verwandeln Sie Markdown mit der Druckfunktion des Browsers in ein durchsuchbares Vektor-PDF. Kein Bitmap, kein Upload, keine Anmeldung.',
    },
    h1: {
      en: 'Free Markdown to PDF Converter',
      'zh-cn': '免费 Markdown 转 PDF 转换器',
      'zh-tw': '免費 Markdown 轉 PDF 轉換器',
      ja: '無料の Markdown → PDF 変換ツール',
      fr: 'Convertisseur Markdown vers PDF gratuit',
      pt: 'Conversor gratuito de Markdown para PDF',
      de: 'Kostenloser Markdown-zu-PDF-Konverter',
    },
    intro: {
      en: 'We use native browser printing instead of canvas screenshots, so text stays selectable, links stay clickable and pages break correctly.',
      'zh-cn': '我们用浏览器原生打印而非画布截图，因此 PDF 里的文字可选中、链接可点击、分页不会截断内容。',
      'zh-tw': '我們用瀏覽器原生列印而非畫布截圖，因此 PDF 裡的文字可選取、連結可點擊、分頁不會截斷內容。',
      ja: 'キャンバスのスクリーンショットではなくブラウザ標準の印刷機能を使うため、文字は選択可能、リンクはクリック可能、改ページで内容が途切れることもありません。',
      fr: 'Nous utilisons l\'impression native du navigateur plutôt qu\'une capture : le texte reste sélectionnable, les liens cliquables et les sauts de page corrects.',
      pt: 'Usamos a impressão nativa do navegador em vez de captura de tela: o texto continua selecionável, os links clicáveis e as quebras de página corretas.',
      de: 'Wir nutzen den nativen Browserdruck statt Screenshots: Text bleibt auswählbar, Links klickbar, Seitenumbrüche korrekt.',
    },
  },
  {
    slug: 'markdown-to-html',
    converter: 'html',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'html',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to HTML',
      'zh-cn': 'Markdown 转 HTML',
      'zh-tw': 'Markdown 轉 HTML',
      ja: 'Markdown → HTML',
      fr: 'Markdown vers HTML',
      pt: 'Markdown para HTML',
      de: 'Markdown zu HTML',
    },
    seoTitle: {
      en: 'Convert Markdown to HTML Online - Free Markdown to HTML',
      'zh-cn': 'Markdown 转 HTML 在线工具 - 免费即时转换',
      'zh-tw': 'Markdown 轉 HTML 線上工具 - 免費即時轉換',
      ja: 'Markdown を HTML に変換 - 無料・即時',
      fr: 'Convertir Markdown en HTML en ligne - Gratuit et instantané',
      pt: 'Converter Markdown para HTML online - Grátis e instantâneo',
      de: 'Markdown in HTML online umwandeln - Kostenlos',
    },
    seoDesc: {
      en: 'Convert Markdown to clean HTML instantly in the browser. Live preview, syntax highlighting, no signup required.',
      'zh-cn': '在浏览器中即时把 Markdown 转成干净的 HTML，支持实时预览与代码高亮，无需注册。',
      'zh-tw': '在瀏覽器中即時把 Markdown 轉成乾淨的 HTML，支援即時預覽與程式碼高亮，無需註冊。',
      ja: 'ブラウザ上で Markdown を即座にクリーンな HTML へ。ライブプレビューとシンタックスハイライト対応、登録不要。',
      fr: 'Convertissez Markdown en HTML propre instantanément dans le navigateur. Aperçu en direct, coloration syntaxique, sans inscription.',
      pt: 'Converta Markdown em HTML limpo instantaneamente no navegador. Visualização ao vivo, destaque de sintaxe, sem cadastro.',
      de: 'Wandeln Sie Markdown sofort im Browser in sauberes HTML um. Live-Vorschau, Syntaxhervorhebung, ohne Anmeldung.',
    },
    h1: {
      en: 'Free Markdown to HTML Converter',
      'zh-cn': '免费 Markdown 转 HTML 转换器',
      'zh-tw': '免費 Markdown 轉 HTML 轉換器',
      ja: '無料の Markdown → HTML 変換ツール',
      fr: 'Convertisseur Markdown vers HTML gratuit',
      pt: 'Conversor gratuito de Markdown para HTML',
      de: 'Kostenloser Markdown-zu-HTML-Konverter',
    },
    intro: {
      en: 'Get sanitized, ready-to-publish HTML with code highlighting and table support. Copy it or download the file.',
      'zh-cn': '输出经过安全清洗、可直接发布的 HTML，支持代码高亮与表格，可复制或下载文件。',
      'zh-tw': '輸出經過安全清洗、可直接發佈的 HTML，支援程式碼高亮與表格，可複製或下載檔案。',
      ja: 'サニタイズ済みでそのまま公開できる HTML を出力。コードハイライトと表に対応し、コピーもダウンロードも可能です。',
      fr: 'Obtenez un HTML nettoyé et prêt à publier, avec coloration du code et gestion des tableaux. Copiez-le ou téléchargez le fichier.',
      pt: 'Receba HTML sanitizado e pronto para publicar, com destaque de código e suporte a tabelas. Copie ou baixe o arquivo.',
      de: 'Erhalten Sie bereinigtes, veröffentlichungsfertiges HTML mit Code-Hervorhebung und Tabellenunterstützung. Kopieren oder herunterladen.',
    },
  },
  {
    slug: 'markdown-to-text',
    converter: 'text',
    direction: 'md-out',
    outputKind: 'text',
    outputExt: 'txt',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to Text',
      'zh-cn': 'Markdown 转纯文本',
      'zh-tw': 'Markdown 轉純文字',
      ja: 'Markdown → プレーンテキスト',
      fr: 'Markdown vers texte',
      pt: 'Markdown para texto',
      de: 'Markdown zu Text',
    },
    seoTitle: {
      en: 'Convert Markdown to Plain Text Online - Free',
      'zh-cn': 'Markdown 转纯文本在线工具 - 免费去格式',
      'zh-tw': 'Markdown 轉純文字線上工具 - 免費去格式',
      ja: 'Markdown をプレーンテキストに変換 - 無料で書式を削除',
      fr: 'Convertir Markdown en texte brut en ligne - Gratuit',
      pt: 'Converter Markdown para texto simples online - Grátis',
      de: 'Markdown in Klartext online umwandeln - Kostenlos',
    },
    seoDesc: {
      en: 'Strip all Markdown syntax and get clean plain text. Free, instant and processed locally in your browser.',
      'zh-cn': '一键去除 Markdown 语法，得到干净的纯文本。免费、即时，全程在浏览器本地处理。',
      'zh-tw': '一鍵去除 Markdown 語法，得到乾淨的純文字。免費、即時，全程在瀏覽器本機處理。',
      ja: 'Markdown の記法をワンクリックで削除し、クリーンなプレーンテキストに。無料・即時、すべてブラウザ内で処理。',
      fr: 'Supprimez toute la syntaxe Markdown et obtenez un texte brut propre. Gratuit, instantané et traité localement dans votre navigateur.',
      pt: 'Remova toda a sintaxe Markdown e obtenha texto simples e limpo. Grátis, instantâneo e processado localmente no navegador.',
      de: 'Entfernen Sie die gesamte Markdown-Syntax und erhalten Sie sauberen Klartext. Kostenlos, sofort und lokal im Browser verarbeitet.',
    },
    h1: {
      en: 'Free Markdown to Plain Text Converter',
      'zh-cn': '免费 Markdown 转纯文本转换器',
      'zh-tw': '免費 Markdown 轉純文字轉換器',
      ja: '無料の Markdown → プレーンテキスト変換ツール',
      fr: 'Convertisseur Markdown vers texte brut gratuit',
      pt: 'Conversor gratuito de Markdown para texto simples',
      de: 'Kostenloser Markdown-zu-Klartext-Konverter',
    },
    intro: {
      en: 'Remove every bit of markup — headings, emphasis, links, code fences — and keep only the readable words.',
      'zh-cn': '去除全部标记语法：标题、强调、链接、代码围栏，只留下可读的正文文字。',
      'zh-tw': '去除全部標記語法：標題、強調、連結、程式碼圍欄，只留下可讀的正文文字。',
      ja: '見出し、強調、リンク、コードフェンスなどの記法をすべて除去し、読みやすい本文だけを残します。',
      fr: 'Retirez toutes les balises — titres, emphase, liens, blocs de code — et ne gardez que les mots lisibles.',
      pt: 'Remova toda a marcação — títulos, ênfase, links, blocos de código — e mantenha apenas as palavras legíveis.',
      de: 'Entfernen Sie jede Auszeichnung — Überschriften, Hervorhebungen, Links, Codeblöcke — und behalten Sie nur den lesbaren Text.',
    },
  },
  {
    slug: 'html-to-markdown',
    converter: 'turndown',
    direction: 'md-in',
    outputKind: 'text',
    outputExt: 'md',
    accept: '.html,.htm',
    inputKind: 'html',
    name: {
      en: 'HTML to Markdown',
      'zh-cn': 'HTML 转 Markdown',
      'zh-tw': 'HTML 轉 Markdown',
      ja: 'HTML → Markdown',
      fr: 'HTML vers Markdown',
      pt: 'HTML para Markdown',
      de: 'HTML zu Markdown',
    },
    seoTitle: {
      en: 'Free HTML to Markdown Converter - Convert HTML to MD Online',
      'zh-cn': '免费 HTML 转 Markdown 在线工具',
      'zh-tw': '免費 HTML 轉 Markdown 線上工具',
      ja: 'HTML を Markdown に変換 - 無料オンラインツール',
      fr: 'Convertisseur HTML vers Markdown gratuit en ligne',
      pt: 'Conversor gratuito de HTML para Markdown online',
      de: 'HTML in Markdown online umwandeln - Kostenlos',
    },
    seoDesc: {
      en: 'Convert HTML to Markdown instantly. Preserves links, images, tables and formatting. No signup required.',
      'zh-cn': '即时把 HTML 转为 Markdown，保留链接、图片、表格与格式，无需注册。',
      'zh-tw': '即時把 HTML 轉為 Markdown，保留連結、圖片、表格與格式，無需註冊。',
      ja: 'HTML を即座に Markdown へ変換。リンク、画像、表、書式を保持します。登録不要。',
      fr: 'Convertissez HTML en Markdown instantanément. Liens, images, tableaux et mise en forme conservés. Sans inscription.',
      pt: 'Converta HTML em Markdown instantaneamente. Preserva links, imagens, tabelas e formatação. Sem cadastro.',
      de: 'Wandeln Sie HTML sofort in Markdown um. Links, Bilder, Tabellen und Formatierung bleiben erhalten. Ohne Anmeldung.',
    },
    h1: {
      en: 'Free HTML to Markdown Converter',
      'zh-cn': '免费 HTML 转 Markdown 转换器',
      'zh-tw': '免費 HTML 轉 Markdown 轉換器',
      ja: '無料の HTML → Markdown 変換ツール',
      fr: 'Convertisseur HTML vers Markdown gratuit',
      pt: 'Conversor gratuito de HTML para Markdown',
      de: 'Kostenloser HTML-zu-Markdown-Konverter',
    },
    intro: {
      en: 'Paste messy HTML from a CMS or an export and get clean, readable Markdown back. Tables and nested lists included.',
      'zh-cn': '粘贴来自 CMS 或导出的杂乱 HTML，得到干净可读的 Markdown，表格与嵌套列表都能正确处理。',
      'zh-tw': '貼上來自 CMS 或匯出的雜亂 HTML，得到乾淨可讀的 Markdown，表格與巢狀清單都能正確處理。',
      ja: 'CMS やエクスポート由来の散らかった HTML を貼り付けるだけで、読みやすい Markdown に。表やネストしたリストも正しく扱います。',
      fr: 'Collez du HTML désordonné issu d\'un CMS ou d\'un export et obtenez un Markdown propre et lisible. Tableaux et listes imbriquées inclus.',
      pt: 'Cole HTML bagunçado de um CMS ou exportação e receba Markdown limpo e legível. Tabelas e listas aninhadas incluídas.',
      de: 'Fügen Sie unordentliches HTML aus einem CMS oder Export ein und erhalten Sie sauberes, lesbares Markdown. Tabellen und verschachtelte Listen inklusive.',
    },
  },
  {
    slug: 'markdown-to-image',
    converter: 'mdToImage',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'png',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to Image',
      'zh-cn': 'Markdown 转图片',
      'zh-tw': 'Markdown 轉圖片',
      ja: 'Markdown → 圖片',
      fr: 'Markdown vers image',
      pt: 'Markdown para imagem',
      de: 'Markdown zu Bild',
    },
    seoTitle: {
      en: 'Markdown to Image - Export MD as PNG Online',
      'zh-cn': 'Markdown 转图片在线工具 - 导出 PNG 长图',
      'zh-tw': 'Markdown 轉圖片線上工具 - 匯出 PNG 長圖',
      ja: 'Markdown を画像に変換 - PNG 書き出し',
      fr: 'Markdown vers image - Exporter en PNG',
      pt: 'Markdown para imagem - Exportar como PNG',
      de: 'Markdown zu Bild - Als PNG exportieren',
    },
    seoDesc: {
      en: 'Turn Markdown into a shareable PNG. Vector-sharp text, code highlighting and math preserved. Free, no upload.',
      'zh-cn': '把 Markdown 转成方便分享的 PNG 长图，文字清晰锐利，保留代码高亮与公式，免费且不上传。',
      'zh-tw': '把 Markdown 轉成方便分享的 PNG 長圖，文字清晰銳利，保留程式碼高亮與公式，免費且不上傳。',
      ja: 'Markdown を共有しやすい PNG に変換。文字は鮮明で、コードハイライトと数式も保持。無料・アップロード不要。',
      fr: 'Transformez Markdown en PNG partageable. Texte net, coloration du code et formules conservées. Gratuit, sans envoi.',
      pt: 'Transforme Markdown em PNG compartilhável. Texto nítido, destaque de código e fórmulas preservados. Grátis, sem upload.',
      de: 'Verwandeln Sie Markdown in ein teilbares PNG. Scharfer Text, Code-Hervorhebung und Formeln bleiben erhalten. Kostenlos, kein Upload.',
    },
    h1: {
      en: 'Free Markdown to Image Converter',
      'zh-cn': '免费 Markdown 转图片转换器',
      'zh-tw': '免費 Markdown 轉圖片轉換器',
      ja: '無料の Markdown → 画像変換ツール',
      fr: 'Convertisseur Markdown vers image gratuit',
      pt: 'Conversor gratuito de Markdown para imagem',
      de: 'Kostenloser Markdown-zu-Bild-Konverter',
    },
    intro: {
      en: 'Export your document as a long PNG for social posts and slides. Text stays sharp because we render vectors, not pixel screenshots.',
      'zh-cn': '把文档导出成适合社交平台与幻灯片的长图。文字保持锐利，因为渲染的是矢量而非像素截图。',
      'zh-tw': '把文件匯出成適合社群平台與簡報的長圖。文字保持銳利，因為渲染的是向量而非像素截圖。',
      ja: 'SNS やスライド向けの縦長 PNG を書き出せます。ベクター描画なので文字が鮮明なままです。',
      fr: 'Exportez votre document en PNG long pour les réseaux sociaux. Le texte reste net grâce au rendu vectoriel.',
      pt: 'Exporte seu documento como PNG longo para redes sociais. O texto fica nítido porque usamos renderização vetorial.',
      de: 'Exportieren Sie Ihr Dokument als langes PNG für Social Media. Der Text bleibt scharf, weil wir Vektoren rendern.',
    },
  },
  {
    slug: 'markdown-to-latex',
    converter: 'latex',
    direction: 'md-out',
    outputKind: 'text',
    outputExt: 'tex',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to LaTeX',
      'zh-cn': 'Markdown 转 LaTeX',
      'zh-tw': 'Markdown 轉 LaTeX',
      ja: 'Markdown → LaTeX',
      fr: 'Markdown vers LaTeX',
      pt: 'Markdown para LaTeX',
      de: 'Markdown zu LaTeX',
    },
    seoTitle: {
      en: 'Markdown to LaTeX Converter - Free Online',
      'zh-cn': 'Markdown 转 LaTeX 在线工具 - 免费',
      'zh-tw': 'Markdown 轉 LaTeX 線上工具 - 免費',
      ja: 'Markdown を LaTeX に変換 - 無料',
      fr: 'Convertisseur Markdown vers LaTeX en ligne',
      pt: 'Conversor de Markdown para LaTeX online',
      de: 'Markdown zu LaTeX online umwandeln',
    },
    seoDesc: {
      en: 'Convert Markdown to LaTeX with sections, tables and verbatim code blocks. Free, instant, runs in your browser.',
      'zh-cn': '把 Markdown 转为 LaTeX，支持章节、表格与 verbatim 代码块。免费、即时，浏览器内完成。',
      'zh-tw': '把 Markdown 轉為 LaTeX，支援章節、表格與 verbatim 程式碼區塊。免費、即時，瀏覽器內完成。',
      ja: 'Markdown を LaTeX に変換。セクション、表、verbatim 環境に対応。無料・即時、ブラウザ内で完結。',
      fr: 'Convertissez Markdown en LaTeX avec sections, tableaux et blocs verbatim. Gratuit, instantané, dans le navigateur.',
      pt: 'Converta Markdown para LaTeX com seções, tabelas e blocos verbatim. Grátis, instantâneo, no navegador.',
      de: 'Wandeln Sie Markdown in LaTeX um mit Abschnitten, Tabellen und Verbatim-Blöcken. Kostenlos, sofort, im Browser.',
    },
    h1: {
      en: 'Free Markdown to LaTeX Converter',
      'zh-cn': '免费 Markdown 转 LaTeX 转换器',
      'zh-tw': '免費 Markdown 轉 LaTeX 轉換器',
      ja: '無料の Markdown → LaTeX 変換ツール',
      fr: 'Convertisseur Markdown vers LaTeX gratuit',
      pt: 'Conversor gratuito de Markdown para LaTeX',
      de: 'Kostenloser Markdown-zu-LaTeX-Konverter',
    },
    intro: {
      en: 'Get a body-only snippet you can paste into your own template. Special characters are escaped so it compiles the first time.',
      'zh-cn': '输出可直接粘贴进你模板的正文片段，特殊字符已转义，一次编译就能过。',
      'zh-tw': '輸出可直接貼進你模板的正文片段，特殊字元已跳脫，一次編譯就能過。',
      ja: '自分のテンプレートに貼り付けられる本文部分のみを出力。特殊文字はエスケープ済みなので一度でコンパイルできます。',
      fr: 'Obtenez un extrait de corps à coller dans votre modèle. Les caractères spéciaux sont échappés pour compiler du premier coup.',
      pt: 'Receba um trecho de corpo para colar no seu modelo. Caracteres especiais escapados para compilar na primeira tentativa.',
      de: 'Erhalten Sie einen reinen Textauszug für Ihre Vorlage. Sonderzeichen sind maskiert, damit es beim ersten Mal kompiliert.',
    },
  },
  {
    slug: 'markdown-to-rst',
    converter: 'rst',
    direction: 'md-out',
    outputKind: 'text',
    outputExt: 'rst',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to reStructuredText',
      'zh-cn': 'Markdown 转 reStructuredText',
      'zh-tw': 'Markdown 轉 reStructuredText',
      ja: 'Markdown → reStructuredText',
      fr: 'Markdown vers reStructuredText',
      pt: 'Markdown para reStructuredText',
      de: 'Markdown zu reStructuredText',
    },
    seoTitle: {
      en: 'Markdown to reStructuredText Converter - Free',
      'zh-cn': 'Markdown 转 reStructuredText 在线工具',
      'zh-tw': 'Markdown 轉 reStructuredText 線上工具',
      ja: 'Markdown を reStructuredText に変換',
      fr: 'Convertisseur Markdown vers reStructuredText',
      pt: 'Conversor de Markdown para reStructuredText',
      de: 'Markdown zu reStructuredText umwandeln',
    },
    seoDesc: {
      en: 'Convert Markdown to reStructuredText for Sphinx and Python docs. Correct heading underlines and list-table output.',
      'zh-cn': '把 Markdown 转为 reStructuredText，用于 Sphinx 与 Python 文档。标题下划线长度正确，表格用 list-table。',
      'zh-tw': '把 Markdown 轉為 reStructuredText，用於 Sphinx 與 Python 文件。標題底線長度正確，表格用 list-table。',
      ja: 'Sphinx や Python ドキュメント向けに reStructuredText へ変換。見出し下線の長さも list-table も正しく出力。',
      fr: 'Convertissez Markdown en reStructuredText pour Sphinx. Soulignements corrects et tableaux en list-table.',
      pt: 'Converta Markdown para reStructuredText para Sphinx. Sublinhados corretos e tabelas em list-table.',
      de: 'Wandeln Sie Markdown in reStructuredText für Sphinx um. Korrekte Unterstreichungen und Tabellen als list-table.',
    },
    h1: {
      en: 'Free Markdown to reStructuredText Converter',
      'zh-cn': '免费 Markdown 转 reStructuredText 转换器',
      'zh-tw': '免費 Markdown 轉 reStructuredText 轉換器',
      ja: '無料の Markdown → reStructuredText 変換ツール',
      fr: 'Convertisseur Markdown vers reStructuredText gratuit',
      pt: 'Conversor gratuito de Markdown para reStructuredText',
      de: 'Kostenloser Markdown-zu-reStructuredText-Konverter',
    },
    intro: {
      en: 'Heading underlines are sized to the title and tables use list-table, so Sphinx will not complain about column widths.',
      'zh-cn': '标题下划线按标题长度生成，表格统一用 list-table，Sphinx 不会因列宽对齐报错。',
      'zh-tw': '標題底線依標題長度產生，表格統一用 list-table，Sphinx 不會因欄寬對齊報錯。',
      ja: '見出し下線は見出しの長さに合わせ、表は list-table を使うため、Sphinx の桁幅エラーが起きません。',
      fr: 'Les soulignements sont dimensionnés au titre et les tableaux utilisent list-table : Sphinx ne râlera pas sur les largeurs.',
      pt: 'Sublinhados dimensionados ao título e tabelas em list-table, para o Sphinx não reclamar da largura.',
      de: 'Unterstreichungen passen zur Überschrift und Tabellen nutzen list-table — Sphinx meckert nicht über Spaltenbreiten.',
    },
  },
  {
    slug: 'markdown-to-confluence',
    converter: 'confluence',
    direction: 'md-out',
    outputKind: 'text',
    outputExt: 'txt',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown to Confluence',
      'zh-cn': 'Markdown 转 Confluence',
      'zh-tw': 'Markdown 轉 Confluence',
      ja: 'Markdown → Confluence',
      fr: 'Markdown vers Confluence',
      pt: 'Markdown para Confluence',
      de: 'Markdown zu Confluence',
    },
    seoTitle: {
      en: 'Markdown to Confluence Wiki Markup Converter',
      'zh-cn': 'Markdown 转 Confluence  wiki 标记在线工具',
      'zh-tw': 'Markdown 轉 Confluence wiki 標記線上工具',
      ja: 'Markdown を Confluence Wiki 記法に変換',
      fr: 'Convertisseur Markdown vers balisage Confluence',
      pt: 'Conversor de Markdown para marcação Confluence',
      de: 'Markdown zu Confluence-Wiki-Markup',
    },
    seoDesc: {
      en: 'Convert Markdown to Confluence wiki markup. Links, tables, code macros and panels translated correctly.',
      'zh-cn': '把 Markdown 转为 Confluence wiki 标记，链接、表格、代码宏都按正确语法转换。',
      'zh-tw': '把 Markdown 轉為 Confluence wiki 標記，連結、表格、程式碼巨集都按正確語法轉換。',
      ja: 'Markdown を Confluence Wiki 記法へ変換。リンク、表、コードマクロも正しい構文に。',
      fr: 'Convertissez Markdown en balisage wiki Confluence. Liens, tableaux et macros de code correctement traduits.',
      pt: 'Converta Markdown para marcação wiki do Confluence. Links, tabelas e macros de código traduzidos corretamente.',
      de: 'Wandeln Sie Markdown in Confluence-Wiki-Markup um. Links, Tabellen und Code-Makros korrekt übersetzt.',
    },
    h1: {
      en: 'Free Markdown to Confluence Converter',
      'zh-cn': '免费 Markdown 转 Confluence 转换器',
      'zh-tw': '免費 Markdown 轉 Confluence 轉換器',
      ja: '無料の Markdown → Confluence 変換ツール',
      fr: 'Convertisseur Markdown vers Confluence gratuit',
      pt: 'Conversor gratuito de Markdown para Confluence',
      de: 'Kostenloser Markdown-zu-Confluence-Konverter',
    },
    intro: {
      en: 'Confluence looks like Markdown but is not: links are [text|url], images are !url! and code lives in a macro.',
      'zh-cn': 'Confluence 语法看着像 Markdown 其实不是：链接是 [文字|地址]，图片是 !地址!，代码要放进宏里。',
      'zh-tw': 'Confluence 語法看著像 Markdown 其實不是：連結是 [文字|網址]，圖片是 !網址!，程式碼要放進巨集。',
      ja: 'Confluence は Markdown に似て非なる記法です。リンクは [テキスト|URL]、画像は !URL!、コードはマクロで囲みます。',
      fr: 'Confluence ressemble à Markdown mais diffère : liens [texte|url], images !url! et code dans une macro.',
      pt: 'Confluence parece Markdown mas não é: links [texto|url], imagens !url! e código em macro.',
      de: 'Confluence ähnelt Markdown, ist es aber nicht: Links [text|url], Bilder !url! und Code in einem Makro.',
    },
  },
  {
    slug: 'latex-to-markdown',
    converter: 'latexToMd',
    direction: 'md-in',
    outputKind: 'text',
    outputExt: 'md',
    accept: '.tex,.latex,.txt',
    inputKind: 'latex',
    name: {
      en: 'LaTeX to Markdown',
      'zh-cn': 'LaTeX 转 Markdown',
      'zh-tw': 'LaTeX 轉 Markdown',
      ja: 'LaTeX → Markdown',
      fr: 'LaTeX vers Markdown',
      pt: 'LaTeX para Markdown',
      de: 'LaTeX zu Markdown',
    },
    seoTitle: {
      en: 'LaTeX to Markdown Converter - Free Online',
      'zh-cn': 'LaTeX 转 Markdown 在线工具 - 免费',
      'zh-tw': 'LaTeX 轉 Markdown 線上工具 - 免費',
      ja: 'LaTeX を Markdown に変換 - 無料',
      fr: 'Convertisseur LaTeX vers Markdown en ligne',
      pt: 'Conversor de LaTeX para Markdown online',
      de: 'LaTeX in Markdown online umwandeln',
    },
    seoDesc: {
      en: 'Convert LaTeX to Markdown. Sections, itemize, verbatim, tabular and citations are translated into Markdown syntax.',
      'zh-cn': '把 LaTeX 转为 Markdown，章节、列表、verbatim、tabular 与引用标记都会正确转换。',
      'zh-tw': '把 LaTeX 轉為 Markdown，章節、清單、verbatim、tabular 與引用標記都會正確轉換。',
      ja: 'LaTeX を Markdown に変換。セクション、itemize、verbatim、tabular、引用も正しく変換します。',
      fr: 'Convertissez LaTeX en Markdown. Sections, listes, verbatim, tabular et citations sont traduits.',
      pt: 'Converta LaTeX para Markdown. Seções, listas, verbatim, tabular e citações são traduzidos.',
      de: 'Wandeln Sie LaTeX in Markdown um. Abschnitte, Listen, Verbatim, Tabellen und Zitate werden übersetzt.',
    },
    h1: {
      en: 'Free LaTeX to Markdown Converter',
      'zh-cn': '免费 LaTeX 转 Markdown 转换器',
      'zh-tw': '免費 LaTeX 轉 Markdown 轉換器',
      ja: '無料の LaTeX → Markdown 変換ツール',
      fr: 'Convertisseur LaTeX vers Markdown gratuit',
      pt: 'Conversor gratuito de LaTeX para Markdown',
      de: 'Kostenloser LaTeX-zu-Markdown-Konverter',
    },
    intro: {
      en: 'Environments are tracked line by line, so \\\\ and & inside verbatim and tabular survive the conversion.',
      'zh-cn': '逐行跟踪环境状态，verbatim 与 tabular 内部的 \\\\ 和 & 不会被误伤。',
      'zh-tw': '逐行追蹤環境狀態，verbatim 與 tabular 內部的 \\\\ 和 & 不會被誤傷。',
      ja: '環境を 1 行ずつ追跡するため、verbatim や tabular 内の \\\\ と & は保護されます。',
      fr: 'Les environnements sont suivis ligne par ligne : \\\\ et & dans verbatim et tabular sont préservés.',
      pt: 'Ambientes rastreados linha a linha: \\\\ e & dentro de verbatim e tabular são preservados.',
      de: 'Umgebungen werden zeilenweise verfolgt, sodass \\\\ und & in verbatim und tabular erhalten bleiben.',
    },
  },
  {
    slug: 'markdown-editor',
    converter: 'editor',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'md',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown Editor',
      'zh-cn': 'Markdown 编辑器',
      'zh-tw': 'Markdown 編輯器',
      ja: 'Markdown エディタ',
      fr: 'Éditeur Markdown',
      pt: 'Editor Markdown',
      de: 'Markdown-Editor',
    },
    seoTitle: {
      en: 'Online Markdown Editor - Live Preview, No Signup',
      'zh-cn': '在线 Markdown 编辑器 - 实时预览、无需注册',
      'zh-tw': '線上 Markdown 編輯器 - 即時預覽、無需註冊',
      ja: 'オンライン Markdown エディタ - ライブプレビュー、登録不要',
      fr: 'Éditeur Markdown en ligne - Aperçu instantané',
      pt: 'Editor Markdown online - Visualização ao vivo',
      de: 'Online-Markdown-Editor - Live-Vorschau',
    },
    seoDesc: {
      en: 'Write Markdown with a live preview on the right. Code highlighting, tables, math and task lists. Download your .md anytime.',
      'zh-cn': '左边写 Markdown，右边实时预览。支持代码高亮、表格、公式与任务列表，随时下载 .md 源文件。',
      'zh-tw': '左邊寫 Markdown，右邊即時預覽。支援程式碼高亮、表格、公式與任務清單，隨時下載 .md 原始檔。',
      ja: '左で書いて右で即時プレビュー。コードハイライト、表、数式、タスクリストに対応。.md はいつでも保存できます。',
      fr: 'Écrivez à gauche, prévisualisez à droite. Coloration du code, tableaux, formules et listes de tâches.',
      pt: 'Escreva à esquerda, visualize à direita. Destaque de código, tabelas, fórmulas e listas de tarefas.',
      de: 'Links schreiben, rechts Live-Vorschau. Code-Hervorhebung, Tabellen, Formeln und Aufgabenlisten.',
    },
    h1: {
      en: 'Free Online Markdown Editor',
      'zh-cn': '免费在线 Markdown 编辑器',
      'zh-tw': '免費線上 Markdown 編輯器',
      ja: '無料のオンライン Markdown エディタ',
      fr: 'Éditeur Markdown en ligne gratuit',
      pt: 'Editor Markdown online grátis',
      de: 'Kostenloser Online-Markdown-Editor',
    },
    intro: {
      en: 'Everything is rendered locally and your draft is kept in this browser, so you can close the tab and come back to it.',
      'zh-cn': '全部在本地渲染，草稿保存在当前浏览器里，关掉标签页回来内容还在。',
      'zh-tw': '全部在本機渲染，草稿儲存在目前瀏覽器裡，關掉分頁回來內容還在。',
      ja: 'すべてローカルで描画し、下書きはブラウザに保存されます。タブを閉じても戻れば続きから書けます。',
      fr: 'Tout est rendu localement et le brouillon reste dans ce navigateur : fermez l\'onglet, revenez, il est là.',
      pt: 'Tudo renderizado localmente e o rascunho fica neste navegador: feche a aba, volte, ele continua lá.',
      de: 'Alles wird lokal gerendert und der Entwurf bleibt in diesem Browser: Tab schließen, zurückkommen, weiterarbeiten.',
    },
  },
  {
    slug: 'word-to-markdown',
    converter: 'wordToMd',
    direction: 'md-in',
    outputKind: 'text',
    outputExt: 'md',
    accept: '.docx',
    inputKind: 'file',
    binary: true,
    name: {
      en: 'Word to Markdown',
      'zh-cn': 'Word 转 Markdown',
      'zh-tw': 'Word 轉 Markdown',
      ja: 'Word → Markdown',
      fr: 'Word vers Markdown',
      pt: 'Word para Markdown',
      de: 'Word zu Markdown',
    },
    seoTitle: {
      en: 'Word to Markdown Converter - Free Docx to MD',
      'zh-cn': 'Word 转 Markdown 在线工具 - 免费 Docx 转 MD',
      'zh-tw': 'Word 轉 Markdown 線上工具 - 免費 Docx 轉 MD',
      ja: 'Word を Markdown に変換 - Docx から MD へ',
      fr: 'Convertisseur Word vers Markdown - Docx gratuit',
      pt: 'Conversor de Word para Markdown - Docx grátis',
      de: 'Word zu Markdown Konverter - Docx kostenlos',
    },
    seoDesc: {
      en: 'Convert .docx files to Markdown in your browser. Headings, tables and lists preserved. Nothing is uploaded.',
      'zh-cn': '在浏览器里把 .docx 转为 Markdown，保留标题、表格与列表，文件不会上传到任何服务器。',
      'zh-tw': '在瀏覽器裡把 .docx 轉為 Markdown，保留標題、表格與清單，檔案不會上傳到任何伺服器。',
      ja: 'ブラウザ内で .docx を Markdown に変換。見出し、表、リストを保持し、アップロードは一切なし。',
      fr: 'Convertissez vos .docx en Markdown dans le navigateur. Titres, tableaux et listes conservés. Rien n\'est envoyé.',
      pt: 'Converta .docx em Markdown no navegador. Títulos, tabelas e listas preservados. Nada é enviado.',
      de: 'Wandeln Sie .docx im Browser in Markdown um. Überschriften, Tabellen und Listen bleiben erhalten. Kein Upload.',
    },
    h1: {
      en: 'Free Word to Markdown Converter',
      'zh-cn': '免费 Word 转 Markdown 转换器',
      'zh-tw': '免費 Word 轉 Markdown 轉換器',
      ja: '無料の Word → Markdown 変換ツール',
      fr: 'Convertisseur Word vers Markdown gratuit',
      pt: 'Conversor gratuito de Word para Markdown',
      de: 'Kostenloser Word-zu-Markdown-Konverter',
    },
    intro: {
      en: 'Drop in a .docx file and get clean Markdown. Only the modern .docx format is supported — old .doc files must be re-saved first.',
      'zh-cn': '拖入 .docx 文件即可得到干净的 Markdown。仅支持新版 .docx，老版 .doc 需要先用 Word 另存。',
      'zh-tw': '拖入 .docx 檔案即可得到乾淨的 Markdown。僅支援新版 .docx，舊版 .doc 需先用 Word 另存。',
      ja: '.docx をドロップするだけでクリーンな Markdown に。旧形式の .doc は Word で保存し直してください。',
      fr: 'Déposez un .docx et obtenez un Markdown propre. Seul le format .docx est géré — les vieux .doc doivent être réenregistrés.',
      pt: 'Arraste um .docx e receba Markdown limpo. Apenas .docx é suportado — .doc antigos precisam ser salvos novamente.',
      de: 'Ziehen Sie eine .docx-Datei hinein und erhalten Sie sauberes Markdown. Nur .docx wird unterstützt — alte .doc müssen neu gespeichert werden.',
    },
  },
  {
    slug: 'pdf-to-markdown',
    converter: 'pdfToMd',
    direction: 'md-in',
    outputKind: 'text',
    outputExt: 'md',
    accept: '.pdf',
    inputKind: 'file',
    binary: true,
    name: {
      en: 'PDF to Markdown',
      'zh-cn': 'PDF 转 Markdown',
      'zh-tw': 'PDF 轉 Markdown',
      ja: 'PDF → Markdown',
      fr: 'PDF vers Markdown',
      pt: 'PDF para Markdown',
      de: 'PDF zu Markdown',
    },
    seoTitle: {
      en: 'PDF to Markdown Converter - Free Online',
      'zh-cn': 'PDF 转 Markdown 在线工具 - 免费',
      'zh-tw': 'PDF 轉 Markdown 線上工具 - 免費',
      ja: 'PDF を Markdown に変換 - 無料',
      fr: 'Convertisseur PDF vers Markdown en ligne',
      pt: 'Conversor de PDF para Markdown online',
      de: 'PDF in Markdown online umwandeln',
    },
    seoDesc: {
      en: 'Extract the text layer of a PDF and turn it into Markdown. Headings detected from font size. Free, no upload.',
      'zh-cn': '抽取 PDF 的文字层并转成 Markdown，按字号自动识别标题层级。免费，文件不上传。',
      'zh-tw': '抽取 PDF 的文字層並轉成 Markdown，依字級自動識別標題層級。免費，檔案不上傳。',
      ja: 'PDF のテキスト層を抽出して Markdown 化。フォントサイズから見出しを推定。無料・アップロード不要。',
      fr: 'Extrayez la couche texte d\'un PDF et convertissez-la en Markdown. Titres détectés par taille de police.',
      pt: 'Extraia a camada de texto do PDF e converta em Markdown. Títulos detectados pelo tamanho da fonte.',
      de: 'Extrahieren Sie die Textebene eines PDF und wandeln Sie sie in Markdown um. Überschriften nach Schriftgröße erkannt.',
    },
    h1: {
      en: 'Free PDF to Markdown Converter',
      'zh-cn': '免费 PDF 转 Markdown 转换器',
      'zh-tw': '免費 PDF 轉 Markdown 轉換器',
      ja: '無料の PDF → Markdown 変換ツール',
      fr: 'Convertisseur PDF vers Markdown gratuit',
      pt: 'Conversor gratuito de PDF para Markdown',
      de: 'Kostenloser PDF-zu-Markdown-Konverter',
    },
    intro: {
      en: 'PDFs have no heading markup, so levels are inferred from font size. Scanned PDFs have no text layer and cannot be read.',
      'zh-cn': 'PDF 里没有标题标记，层级只能靠字号推断。扫描件没有文字层，无法读取，需要先做 OCR。',
      'zh-tw': 'PDF 裡沒有標題標記，層級只能靠字級推斷。掃描檔沒有文字層，無法讀取，需先做 OCR。',
      ja: 'PDF に見出し情報はないため、フォントサイズから階層を推定します。スキャン PDF はテキスト層がなく読めません。',
      fr: 'Les PDF n\'ont pas de balises de titre : les niveaux sont déduits de la taille de police. Les PDF scannés sont illisibles.',
      pt: 'PDFs não têm marcação de título: os níveis são inferidos pelo tamanho da fonte. PDFs digitalizados não têm texto.',
      de: 'PDFs kennen keine Überschriften — die Ebenen werden aus der Schriftgröße abgeleitet. Gescannte PDFs haben keine Textebene.',
    },
  },
  {
    slug: 'csv-to-markdown-table',
    converter: 'csvToTable',
    direction: 'md-in',
    outputKind: 'text',
    outputExt: 'md',
    accept: '.csv,.tsv,.txt',
    inputKind: 'csv',
    name: {
      en: 'CSV to Markdown Table',
      'zh-cn': 'CSV 转 Markdown 表格',
      'zh-tw': 'CSV 轉 Markdown 表格',
      ja: 'CSV → Markdown テーブル',
      fr: 'CSV vers tableau Markdown',
      pt: 'CSV para tabela Markdown',
      de: 'CSV zu Markdown-Tabelle',
    },
    seoTitle: {
      en: 'CSV to Markdown Table Converter - Free Online',
      'zh-cn': 'CSV 转 Markdown 表格在线工具 - 免费',
      'zh-tw': 'CSV 轉 Markdown 表格線上工具 - 免費',
      ja: 'CSV を Markdown テーブルに変換 - 無料',
      fr: 'Convertisseur CSV vers tableau Markdown',
      pt: 'Conversor de CSV para tabela Markdown',
      de: 'CSV zu Markdown-Tabelle umwandeln',
    },
    seoDesc: {
      en: 'Paste CSV or TSV and get a Markdown table. The delimiter is detected automatically and quoted fields are handled.',
      'zh-cn': '粘贴 CSV 或 TSV 直接得到 Markdown 表格，自动识别分隔符，正确处理带引号的字段。',
      'zh-tw': '貼上 CSV 或 TSV 直接得到 Markdown 表格，自動識別分隔符，正確處理含引號的欄位。',
      ja: 'CSV / TSV を貼り付けるだけで Markdown テーブルに。区切り文字は自動判定、引用符付き項目も処理。',
      fr: 'Collez du CSV ou TSV et obtenez un tableau Markdown. Le délimiteur est détecté automatiquement.',
      pt: 'Cole CSV ou TSV e receba uma tabela Markdown. O delimitador é detectado automaticamente.',
      de: 'CSV oder TSV einfügen und eine Markdown-Tabelle erhalten. Das Trennzeichen wird automatisch erkannt.',
    },
    h1: {
      en: 'Free CSV to Markdown Table Converter',
      'zh-cn': '免费 CSV 转 Markdown 表格转换器',
      'zh-tw': '免費 CSV 轉 Markdown 表格轉換器',
      ja: '無料の CSV → Markdown テーブル変換ツール',
      fr: 'Convertisseur CSV vers tableau Markdown gratuit',
      pt: 'Conversor gratuito de CSV para tabela Markdown',
      de: 'Kostenloser CSV-zu-Markdown-Tabellen-Konverter',
    },
    intro: {
      en: 'The first row becomes the header. Commas inside quoted fields are kept intact instead of splitting the column.',
      'zh-cn': '第一行作为表头。引号内的逗号不会被误当作分隔符，字段内容完整保留。',
      'zh-tw': '第一列作為表頭。引號內的逗號不會被誤當分隔符，欄位內容完整保留。',
      ja: '1 行目がヘッダーになります。引用符内のカンマで列が分割されることはありません。',
      fr: 'La première ligne devient l\'en-tête. Les virgules entre guillemets ne coupent pas la colonne.',
      pt: 'A primeira linha vira cabeçalho. Vírgulas entre aspas não dividem a coluna.',
      de: 'Die erste Zeile wird zur Kopfzeile. Kommas in Anführungszeichen trennen die Spalte nicht.',
    },
  },
  {
    slug: 'json-to-markdown-table',
    converter: 'jsonToTable',
    direction: 'md-in',
    outputKind: 'text',
    outputExt: 'md',
    accept: '.json,.txt',
    inputKind: 'json',
    name: {
      en: 'JSON to Markdown Table',
      'zh-cn': 'JSON 转 Markdown 表格',
      'zh-tw': 'JSON 轉 Markdown 表格',
      ja: 'JSON → Markdown テーブル',
      fr: 'JSON vers tableau Markdown',
      pt: 'JSON para tabela Markdown',
      de: 'JSON zu Markdown-Tabelle',
    },
    seoTitle: {
      en: 'JSON to Markdown Table Converter - Free Online',
      'zh-cn': 'JSON 转 Markdown 表格在线工具 - 免费',
      'zh-tw': 'JSON 轉 Markdown 表格線上工具 - 免費',
      ja: 'JSON を Markdown テーブルに変換 - 無料',
      fr: 'Convertisseur JSON vers tableau Markdown',
      pt: 'Conversor de JSON para tabela Markdown',
      de: 'JSON zu Markdown-Tabelle umwandeln',
    },
    seoDesc: {
      en: 'Turn an array of JSON objects into a Markdown table. Missing fields become empty cells so columns stay aligned.',
      'zh-cn': '把 JSON 对象数组转成 Markdown 表格，缺失字段填为空单元格，列不会错位。',
      'zh-tw': '把 JSON 物件陣列轉成 Markdown 表格，缺失欄位填為空儲存格，欄位不會錯位。',
      ja: 'JSON オブジェクトの配列を Markdown テーブルに。欠損フィールドは空セルになり列がずれません。',
      fr: 'Transformez un tableau d\'objets JSON en tableau Markdown. Les champs manquants deviennent des cellules vides.',
      pt: 'Transforme um array de objetos JSON em tabela Markdown. Campos ausentes viram células vazias.',
      de: 'Verwandeln Sie ein JSON-Objekt-Array in eine Markdown-Tabelle. Fehlende Felder werden leere Zellen.',
    },
    h1: {
      en: 'Free JSON to Markdown Table Converter',
      'zh-cn': '免费 JSON 转 Markdown 表格转换器',
      'zh-tw': '免費 JSON 轉 Markdown 表格轉換器',
      ja: '無料の JSON → Markdown テーブル変換ツール',
      fr: 'Convertisseur JSON vers tableau Markdown gratuit',
      pt: 'Conversor gratuito de JSON para tabela Markdown',
      de: 'Kostenloser JSON-zu-Markdown-Tabellen-Konverter',
    },
    intro: {
      en: 'Paste an API response or exported data. Nested objects are stringified so nothing disappears silently.',
      'zh-cn': '直接粘贴接口返回值或导出数据。嵌套对象会被序列化成字符串，不会静默丢失。',
      'zh-tw': '直接貼上 API 回傳值或匯出資料。巢狀物件會被序列化成字串，不會靜默遺失。',
      ja: 'API レスポンスやエクスポートデータを貼り付け可能。ネストしたオブジェクトは文字列化され、黙って消えることはありません。',
      fr: 'Collez une réponse d\'API ou des données exportées. Les objets imbriqués sont sérialisés sans perte.',
      pt: 'Cole uma resposta de API ou dados exportados. Objetos aninhados são serializados sem perda.',
      de: 'Fügen Sie eine API-Antwort oder Exportdaten ein. Verschachtelte Objekte werden serialisiert, nichts verschwindet.',
    },
  },
  {
    slug: 'markdown-table-to-csv',
    converter: 'tableToCsv',
    direction: 'md-out',
    outputKind: 'text',
    outputExt: 'csv',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown Table to CSV',
      'zh-cn': 'Markdown 表格转 CSV',
      'zh-tw': 'Markdown 表格轉 CSV',
      ja: 'Markdown テーブル → CSV',
      fr: 'Tableau Markdown vers CSV',
      pt: 'Tabela Markdown para CSV',
      de: 'Markdown-Tabelle zu CSV',
    },
    seoTitle: {
      en: 'Markdown Table to CSV Converter - Free Online',
      'zh-cn': 'Markdown 表格转 CSV 在线工具 - 免费',
      'zh-tw': 'Markdown 表格轉 CSV 線上工具 - 免費',
      ja: 'Markdown テーブルを CSV に変換 - 無料',
      fr: 'Convertisseur tableau Markdown vers CSV',
      pt: 'Conversor de tabela Markdown para CSV',
      de: 'Markdown-Tabelle in CSV umwandeln',
    },
    seoDesc: {
      en: 'Extract the first table from a Markdown document and export it as CSV. Ready for Excel and Google Sheets.',
      'zh-cn': '从 Markdown 文档中提取表格并导出为 CSV，可直接用 Excel 或 Google 表格打开。',
      'zh-tw': '從 Markdown 文件中擷取表格並匯出為 CSV，可直接用 Excel 或 Google 試算表開啟。',
      ja: 'Markdown 文書から表を抽出して CSV に。Excel や Google スプレッドシートでそのまま開けます。',
      fr: 'Extrayez le premier tableau d\'un document Markdown et exportez-le en CSV. Prêt pour Excel.',
      pt: 'Extraia a primeira tabela de um documento Markdown e exporte como CSV. Pronto para Excel.',
      de: 'Extrahieren Sie die erste Tabelle aus einem Markdown-Dokument und exportieren Sie sie als CSV. Bereit für Excel.',
    },
    h1: {
      en: 'Free Markdown Table to CSV Converter',
      'zh-cn': '免费 Markdown 表格转 CSV 转换器',
      'zh-tw': '免費 Markdown 表格轉 CSV 轉換器',
      ja: '無料の Markdown テーブル → CSV 変換ツール',
      fr: 'Convertisseur tableau Markdown vers CSV gratuit',
      pt: 'Conversor gratuito de tabela Markdown para CSV',
      de: 'Kostenloser Markdown-Tabelle-zu-CSV-Konverter',
    },
    intro: {
      en: 'Paste the whole document, not just the table. We find the first table even if it sits inside a blockquote or list.',
      'zh-cn': '可以直接粘贴整篇文档，不必只挑表格。即使表格藏在引用或列表里也能找到。',
      'zh-tw': '可以直接貼上整份文件，不必只挑表格。即使表格藏在引用或清單裡也能找到。',
      ja: 'ドキュメント全体を貼り付けて構いません。引用やリストの中にある表も検出します。',
      fr: 'Collez le document entier : nous trouvons le premier tableau même dans une citation ou une liste.',
      pt: 'Cole o documento inteiro: encontramos a primeira tabela mesmo dentro de citação ou lista.',
      de: 'Fügen Sie das ganze Dokument ein — wir finden die erste Tabelle auch in Zitaten oder Listen.',
    },
  },
  {
    slug: 'markdown-table-to-pdf',
    converter: 'tableToPdf',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'pdf',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown Table to PDF',
      'zh-cn': 'Markdown 表格转 PDF',
      'zh-tw': 'Markdown 表格轉 PDF',
      ja: 'Markdown テーブル → PDF',
      fr: 'Tableau Markdown vers PDF',
      pt: 'Tabela Markdown para PDF',
      de: 'Markdown-Tabelle zu PDF',
    },
    seoTitle: {
      en: 'Markdown Table to PDF - Free Online Converter',
      'zh-cn': 'Markdown 表格转 PDF 在线工具 - 免费',
      'zh-tw': 'Markdown 表格轉 PDF 線上工具 - 免費',
      ja: 'Markdown テーブルを PDF に変換 - 無料',
      fr: 'Convertisseur tableau Markdown vers PDF',
      pt: 'Conversor de tabela Markdown para PDF',
      de: 'Markdown-Tabelle in PDF umwandeln',
    },
    seoDesc: {
      en: 'Export a Markdown table as a clean PDF using the browser print engine. Text stays selectable and searchable.',
      'zh-cn': '用浏览器打印引擎把 Markdown 表格导出为干净的 PDF，文字保持可选中、可搜索。',
      'zh-tw': '用瀏覽器列印引擎把 Markdown 表格匯出為乾淨的 PDF，文字保持可選取、可搜尋。',
      ja: 'ブラウザの印刷エンジンで Markdown テーブルを PDF に。文字は選択・検索可能なままです。',
      fr: 'Exportez un tableau Markdown en PDF via le moteur d\'impression. Le texte reste sélectionnable.',
      pt: 'Exporte uma tabela Markdown como PDF com o motor de impressão. O texto continua selecionável.',
      de: 'Exportieren Sie eine Markdown-Tabelle über die Druckfunktion als PDF. Der Text bleibt auswählbar.',
    },
    h1: {
      en: 'Free Markdown Table to PDF Converter',
      'zh-cn': '免费 Markdown 表格转 PDF 转换器',
      'zh-tw': '免費 Markdown 表格轉 PDF 轉換器',
      ja: '無料の Markdown テーブル → PDF 変換ツール',
      fr: 'Convertisseur tableau Markdown vers PDF gratuit',
      pt: 'Conversor gratuito de tabela Markdown para PDF',
      de: 'Kostenloser Markdown-Tabelle-zu-PDF-Konverter',
    },
    intro: {
      en: 'Same vector print pipeline as the document exporter, so tables do not get sliced in half across pages.',
      'zh-cn': '与文档导出同一套矢量打印管线，表格不会在跨页时被从中间切断。',
      'zh-tw': '與文件匯出同一套向量列印管線，表格不會在跨頁時被從中間切斷。',
      ja: '文書書き出しと同じベクター印刷経路を使うため、表がページ境界で途中切断されません。',
      fr: 'Le même moteur vectoriel que l\'export de document : les tableaux ne sont pas coupés entre deux pages.',
      pt: 'O mesmo pipeline vetorial do exportador de documentos: as tabelas não são cortadas entre páginas.',
      de: 'Dieselbe Vektor-Druckpipeline wie beim Dokumentexport — Tabellen werden nicht mittig getrennt.',
    },
  },
  {
    slug: 'markdown-table-to-image',
    converter: 'tableToImage',
    direction: 'md-out',
    outputKind: 'html',
    outputExt: 'png',
    accept: '.md,.markdown,.txt',
    inputKind: 'md',
    name: {
      en: 'Markdown Table to Image',
      'zh-cn': 'Markdown 表格转图片',
      'zh-tw': 'Markdown 表格轉圖片',
      ja: 'Markdown テーブル → 画像',
      fr: 'Tableau Markdown vers image',
      pt: 'Tabela Markdown para imagem',
      de: 'Markdown-Tabelle zu Bild',
    },
    seoTitle: {
      en: 'Markdown Table to PNG - Free Online Converter',
      'zh-cn': 'Markdown 表格转 PNG 在线工具 - 免费',
      'zh-tw': 'Markdown 表格轉 PNG 線上工具 - 免費',
      ja: 'Markdown テーブルを PNG に変換 - 無料',
      fr: 'Convertisseur tableau Markdown vers PNG',
      pt: 'Conversor de tabela Markdown para PNG',
      de: 'Markdown-Tabelle in PNG umwandeln',
    },
    seoDesc: {
      en: 'Render a Markdown table as a crisp PNG for slides and docs. Column widths fit the content automatically.',
      'zh-cn': '把 Markdown 表格渲染成清晰锐利的 PNG，适合幻灯片与文档，列宽按内容自动适配。',
      'zh-tw': '把 Markdown 表格渲染成清晰銳利的 PNG，適合簡報與文件，欄寬依內容自動調整。',
      ja: 'Markdown テーブルを鮮明な PNG に。列幅は内容に合わせて自動調整されます。',
      fr: 'Rendez un tableau Markdown en PNG net. La largeur des colonnes s\'adapte au contenu.',
      pt: 'Renderize uma tabela Markdown como PNG nítido. A largura das colunas se ajusta ao conteúdo.',
      de: 'Rendern Sie eine Markdown-Tabelle als klares PNG. Die Spaltenbreite passt sich dem Inhalt an.',
    },
    h1: {
      en: 'Free Markdown Table to Image Converter',
      'zh-cn': '免费 Markdown 表格转图片转换器',
      'zh-tw': '免費 Markdown 表格轉圖片轉換器',
      ja: '無料の Markdown テーブル → 画像変換ツール',
      fr: 'Convertisseur tableau Markdown vers image gratuit',
      pt: 'Conversor gratuito de tabela Markdown para imagem',
      de: 'Kostenloser Markdown-Tabelle-zu-Bild-Konverter',
    },
    intro: {
      en: 'Drawn on a canvas rather than screenshotted, so text stays sharp at any zoom level and CJK characters render correctly.',
      'zh-cn': '用 Canvas 直接绘制而非截图，任何缩放级别下文字都锐利，中日韩字符也能正确渲染。',
      'zh-tw': '用 Canvas 直接繪製而非截圖，任何縮放層級下文字都銳利，中日韓字元也能正確渲染。',
      ja: 'スクリーンショットではなく Canvas 描画なので、どの倍率でも文字が鮮明で CJK も正しく表示されます。',
      fr: 'Dessiné sur canvas plutôt que capturé : le texte reste net à tout zoom et les caractères CJK s\'affichent bien.',
      pt: 'Desenhado em canvas em vez de capturado: o texto fica nítido em qualquer zoom e caracteres CJK funcionam.',
      de: 'Auf Canvas gezeichnet statt abfotografiert — Text bleibt scharf und CJK-Zeichen werden korrekt dargestellt.',
    },
  },
];

export function getTool(slug: string): ToolDef | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

/** 供 getStaticPaths 使用：工具 × 语言 的全部组合 */
export function toolPaths() {
  return TOOLS.flatMap((tool) =>
    (['en', 'zh-cn', 'zh-tw', 'ja', 'fr', 'pt', 'de'] as Lang[]).map((lang) => ({
      params: { lang, tool: tool.slug },
      props: { tool },
    })),
  );
}
